POST http://localhost:9000/api/student/register HTTP/1.1
content-Type: application/json

{
    "name":"sp",
    "email":"sp12@gmail.com",
    "password":"1212",
    "phone":"1212450450"
}
###

POST http://localhost:9000/api/student/login HTTP/1.1
content-Type: application/json

{
    "email":"sp12@gmail.com",
    "password":"1212"
}
###
POST http://localhost:9000/api/student/register HTTP/1.1
content-Type: application/json

{
    "name":"ram",
    "email":"ram12@gmail.com",
    "password":"2121",
    "phone":"1234567890"
}

###
POST http://localhost:9000/api/student/login HTTP/1.1
content-Type: application/json

{
    "email":"ram12@gmail.com",
    "password":"2121"
}


###
POST http://localhost:9000/api/admin/register HTTP/1.1
content-Type: application/json

{
    "name":"harrybhav",
    "email":"harry@gmail.com",
    "password":"12"
}


###
POST http://localhost:9000/api/admin/login HTTP/1.1
content-Type: application/json

{
    "email":"harry@gmail.com",
    "password":"12"
}

###
GEt http://localhost:9000/api/admin/students HTTP/1.1
content-Type: application/json

{
    header:{

    }
}
